---
swagger: "2.0"
info:
  description: "NetEaseCloudMusic Service"
  version: "v1"
  title: "NetEaseCloudMusic Service"
  contact:
    name: "Xiong Tianlei"
    email: "1410661066@qq.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost"
basePath: "/music"
schemes:
- "http"
paths:
  /music/getFavorSingers:
    post:
      operationId: "getFavorSingers"
      parameters:
      - name: "ph"
        in: "query"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              type: "object"
  /music/getFavorSong:
    post:
      operationId: "getFavorSong"
      parameters:
      - name: "ph"
        in: "query"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/musics"
  /music/getSimiSongs:
    get:
      operationId: "getSimiSongs"
      parameters:
      - name: "mid"
        in: "query"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              type: "object"
  /music/gethistorybyid:
    post:
      operationId: "gethistorybyid"
      parameters:
      - name: "page"
        in: "query"
        required: true
        type: "integer"
        format: "int32"
      - name: "size"
        in: "query"
        required: true
        type: "integer"
        format: "int32"
      - name: "id"
        in: "query"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/PageWyyuser"
  /music/gethistorybypage:
    post:
      operationId: "gethistorybypage"
      parameters:
      - name: "page"
        in: "query"
        required: true
        type: "integer"
        format: "int32"
      - name: "size"
        in: "query"
        required: true
        type: "integer"
        format: "int32"
      - name: "ph"
        in: "query"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/PageWyyuser"
  /music/getid:
    post:
      operationId: "getid"
      parameters:
      - name: "ph"
        in: "query"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "integer"
            format: "int64"
  /music/updatehistory:
    post:
      operationId: "updatehistory"
      parameters:
      - name: "ph"
        in: "query"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "boolean"
  /music/updatehistorybyid:
    post:
      operationId: "updatehistorybyid"
      parameters:
      - name: "id"
        in: "query"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "boolean"
definitions:
  Page:
    type: "object"
    properties:
      totalElements:
        type: "integer"
        format: "int64"
      totalPages:
        type: "integer"
        format: "int32"
      number:
        type: "integer"
        format: "int32"
      size:
        type: "integer"
        format: "int32"
      content:
        type: "array"
        items:
          type: "object"
      last:
        type: "boolean"
      pageable:
        $ref: "#/definitions/Pageable"
      sort:
        $ref: "#/definitions/Sort"
      first:
        type: "boolean"
      numberOfElements:
        type: "integer"
        format: "int32"
      empty:
        type: "boolean"
  PageWyyuser:
    type: "object"
    properties:
      totalElements:
        type: "integer"
        format: "int64"
      totalPages:
        type: "integer"
        format: "int32"
      number:
        type: "integer"
        format: "int32"
      size:
        type: "integer"
        format: "int32"
      content:
        type: "array"
        items:
          $ref: "#/definitions/wyyuser"
      last:
        type: "boolean"
      pageable:
        $ref: "#/definitions/Pageable"
      sort:
        $ref: "#/definitions/Sort"
      first:
        type: "boolean"
      numberOfElements:
        type: "integer"
        format: "int32"
      empty:
        type: "boolean"
  Pageable:
    type: "object"
    properties:
      offset:
        type: "integer"
        format: "int64"
      paged:
        type: "boolean"
      pageNumber:
        type: "integer"
        format: "int32"
      pageSize:
        type: "integer"
        format: "int32"
      unpaged:
        type: "boolean"
      sort:
        $ref: "#/definitions/Sort"
  Sort:
    type: "object"
    properties:
      sorted:
        type: "boolean"
      unsorted:
        type: "boolean"
      empty:
        type: "boolean"
  musics:
    type: "object"
    properties:
      mid:
        type: "integer"
        format: "int64"
      mname:
        type: "string"
      style:
        type: "string"
      times:
        type: "string"
      singers:
        type: "array"
        items:
          $ref: "#/definitions/sing"
  sing:
    type: "object"
    properties:
      singid:
        type: "integer"
        format: "int64"
      mid:
        type: "integer"
        format: "int64"
      sid:
        type: "integer"
        format: "int64"
      sname:
        type: "string"
  wyyuser:
    type: "object"
    properties:
      hisid:
        type: "integer"
        format: "int64"
      wyyid:
        type: "integer"
        format: "int64"
      musics:
        $ref: "#/definitions/musics"
      playcount:
        type: "integer"
        format: "int32"
      score:
        type: "integer"
        format: "int32"
