server:
  port: 8090
spring:
  application:
    name: zuul-proxy
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://18.166.111.161:1001/eureka/

zuul:
  add-host-header: true #设置为true重定向是会添加host请求头
  routes: #给服务配置路由
    music-service:
      service-id: music-service
      path: /music-service/**
      sensitive-headers:
    taobao:
      path: /taobao/**  ## 匹配的路径
      service-id: taobao-service ## 转到的路径
      url: http://18.166.111.161:8095
      sensitive-headers: 