version: '3.2'

services:
    config-server:
        image: ilife2020/config-server
        ports:
            - "8888:8888"
    registry:
        image: ilife2020/registry
        ports:
            - "1001:8090"
    gateway:
        image: ilife2020/gateway
        ports:
            - "8000:8090"
    redis: 
        image: redis
        ports:
            - "6379:6379"
    auth:
        image: ilife2020/auth-service
        ports:
            - "8686:8080"