apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: ilife2020/registry:latest
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: registry-service
spec: 
  selector:
      app: registry
  ports:
    - port: 8090
      targetPort: 8090
      nodePort: 31001
  type: NodePort 