apiVersion: v1
kind: Deployment
metadata:
  name: zhihu-service
  labels: 
    name: zhihu-service
spec:
  replicas: 2
  template:
    metadata:
      labels: 
        node: zhihu-service
    spec: 
      containers:
      - name: zhihu-service
        image: ilife2020/zhihu-service
        port: 
        - containerPort: 8094
---
apiVersion: v1
kind: Service
metadata:
  name: zhihu-service-service
spec: 
  selector:
    node: zhihu-service
  ports:
    - port: 8090
      targetPort: 8094
      nodePort: 8200
  type: NodePort