---
swagger: "2.0"
info:
  description: "Weibo Service API"
  version: "v2"
  title: "Weibo Service"
  contact:
    name: "Yang Gen"
    email: "zhull991122@sjtu.edu.cn"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost"
basePath: "/"
tags:
- name: "pet"
- name: "User Service Controller"
schemes:
- "http"
paths:
  /user/delById:
    get:
      tags:
      - "User Service Controller"
      summary: "delete one user"
      description: "Delete one user info specified by userId"
      operationId: "delUserByUserId"
      parameters:
      - name: "userId"
        in: "query"
        description: "The user ID of a WeiBo user,should be a Long Integer"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
  /user/getById:
    get:
      tags:
      - "User Service Controller"
      summary: "get user info"
      description: "Get user info by userID"
      operationId: "getUserById"
      parameters:
      - name: "userId"
        in: "query"
        description: "The user ID of a WeiBo user,should be a Long Integer"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/User"
  /user/getByName:
    get:
      tags:
      - "User Service Controller"
      summary: "get user info"
      description: "Get user info by nickname"
      operationId: "getUserByNickname"
      parameters:
      - name: "nickname"
        in: "query"
        description: "The nickname of a WeiBo user,should be a String"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/User"
  /weibo/deleteWeibo:
    get:
      tags:
      - "pet"
      summary: "delete one Weibo"
      description: "Delete one Weibos from database specified by Weibo ID,success\
        \ if the response.status = 200 "
      operationId: "deleteWeibo"
      parameters:
      - name: "Id"
        in: "query"
        description: "The ID of a WeiBo,should be a String"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
        501:
          description: "weiboId not exists"
  /weibo/deleteWeibos:
    get:
      tags:
      - "pet"
      summary: "delete one user's Weibos"
      description: "Delete all Weibos from database of one user specified by userID,success\
        \ if the response.status = 200 "
      operationId: "deleteWeibos"
      parameters:
      - name: "userId"
        in: "query"
        description: "The user ID of a WeiBo user,should be a Long Integer"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
        501:
          description: "userId not exists"
  /weibo/getPages:
    get:
      tags:
      - "pet"
      summary: "get one user's Weibos"
      description: "Get part of Weibos from database of one user specified by userID"
      operationId: "getPages"
      parameters:
      - name: "userId"
        in: "query"
        description: "The user ID of a WeiBo user,should be a Long Integer"
        required: true
        type: "integer"
        format: "int64"
      - name: "page"
        in: "query"
        required: true
        type: "integer"
        format: "int32"
      - name: "size"
        in: "query"
        required: true
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/PageWeibo"
  /weibo/getStats:
    get:
      tags:
      - "pet"
      summary: "get weibo statistics"
      description: "Get user's weibo statistics specified by userID"
      operationId: "getStats"
      parameters:
      - name: "userId"
        in: "query"
        description: "The user ID of a WeiBo user,should be a Long Integer"
        required: true
        type: "integer"
        format: "int64"
      - name: "startTime"
        in: "query"
        required: true
        type: "string"
        format: "date-time"
      - name: "endTime"
        in: "query"
        required: true
        type: "string"
        format: "date-time"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Statistics"
  /weibo/getWeibo:
    get:
      tags:
      - "pet"
      summary: "get one Weibo"
      description: "Get One Weibo from database specified by Weibo ID"
      operationId: "getWeibo"
      parameters:
      - name: "Id"
        in: "query"
        description: "The ID of a WeiBo,should be a String"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Weibo"
  /weibo/getWeibos:
    get:
      tags:
      - "pet"
      summary: "get one user's Weibos"
      description: "Get all Weibos from database of one user specified by userID"
      operationId: "getWeibos"
      parameters:
      - name: "userId"
        in: "query"
        description: "The user ID of a WeiBo user,should be a Long Integer"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Weibo"
definitions:
  Page:
    type: "object"
    properties:
      totalPages:
        type: "integer"
        format: "int32"
      totalElements:
        type: "integer"
        format: "int64"
      number:
        type: "integer"
        format: "int32"
      size:
        type: "integer"
        format: "int32"
      content:
        type: "array"
        items:
          type: "object"
      sort:
        $ref: "#/definitions/Sort"
      first:
        type: "boolean"
      pageable:
        $ref: "#/definitions/Pageable"
      last:
        type: "boolean"
      numberOfElements:
        type: "integer"
        format: "int32"
      empty:
        type: "boolean"
  PageWeibo:
    type: "object"
    properties:
      totalPages:
        type: "integer"
        format: "int32"
      totalElements:
        type: "integer"
        format: "int64"
      number:
        type: "integer"
        format: "int32"
      size:
        type: "integer"
        format: "int32"
      content:
        type: "array"
        items:
          $ref: "#/definitions/Weibo"
      sort:
        $ref: "#/definitions/Sort"
      first:
        type: "boolean"
      pageable:
        $ref: "#/definitions/Pageable"
      last:
        type: "boolean"
      numberOfElements:
        type: "integer"
        format: "int32"
      empty:
        type: "boolean"
  Pageable:
    type: "object"
    properties:
      offset:
        type: "integer"
        format: "int64"
      sort:
        $ref: "#/definitions/Sort"
      pageNumber:
        type: "integer"
        format: "int32"
      paged:
        type: "boolean"
      unpaged:
        type: "boolean"
      pageSize:
        type: "integer"
        format: "int32"
  Sort:
    type: "object"
    properties:
      sorted:
        type: "boolean"
      unsorted:
        type: "boolean"
      empty:
        type: "boolean"
  Statistics:
    type: "object"
    properties:
      avgUp:
        type: "number"
        format: "float"
      maxUp:
        type: "integer"
        format: "int32"
      allUp:
        type: "integer"
        format: "int32"
      maxUpWb:
        type: "string"
      avgRt:
        type: "number"
        format: "float"
      maxRt:
        type: "integer"
        format: "int32"
      allRt:
        type: "integer"
        format: "int32"
      maxRtWb:
        type: "string"
      avgCm:
        type: "number"
        format: "float"
      maxCm:
        type: "integer"
        format: "int32"
      allCm:
        type: "integer"
        format: "int32"
      maxCmWb:
        type: "string"
      avgWb:
        type: "number"
        format: "float"
      maxWb:
        type: "integer"
        format: "int32"
      allWb:
        type: "integer"
        format: "int32"
      maxDate:
        type: "string"
        format: "date-time"
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      nickname:
        type: "string"
      followers:
        type: "integer"
        format: "int32"
      following:
        type: "integer"
        format: "int32"
      weibo_num:
        type: "integer"
        format: "int32"
      birthday:
        type: "string"
      gender:
        type: "string"
      location:
        type: "string"
      description:
        type: "string"
      education:
        type: "string"
      work:
        type: "string"
      avatar:
        type: "string"
  Weibo:
    type: "object"
    properties:
      id:
        type: "string"
      uid:
        type: "integer"
        format: "int64"
      content:
        type: "string"
      publish_place:
        type: "string"
      retweet_num:
        type: "integer"
        format: "int32"
      comment_count:
        type: "integer"
        format: "int32"
      up_num:
        type: "integer"
        format: "int32"
      publish_time:
        type: "string"
        format: "date-time"
