# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import zhihu_pb2 as zhihu__pb2


class ZhihuServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/ZhihuService/Login',
                request_serializer=zhihu__pb2.LoginRequest.SerializeToString,
                response_deserializer=zhihu__pb2.LoginResponse.FromString,
                )
        self.GetActivity = channel.unary_unary(
                '/ZhihuService/GetActivity',
                request_serializer=zhihu__pb2.ActivitiyRequest.SerializeToString,
                response_deserializer=zhihu__pb2.ActivityResponse.FromString,
                )


class ZhihuServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActivity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ZhihuServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=zhihu__pb2.LoginRequest.FromString,
                    response_serializer=zhihu__pb2.LoginResponse.SerializeToString,
            ),
            'GetActivity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActivity,
                    request_deserializer=zhihu__pb2.ActivitiyRequest.FromString,
                    response_serializer=zhihu__pb2.ActivityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ZhihuService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ZhihuService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ZhihuService/Login',
            zhihu__pb2.LoginRequest.SerializeToString,
            zhihu__pb2.LoginResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetActivity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ZhihuService/GetActivity',
            zhihu__pb2.ActivitiyRequest.SerializeToString,
            zhihu__pb2.ActivityResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
